label one:
    play music  "bgm/尴尬.opus" 
    scene library with rule_1
    show luokun xiaosa with dissolve
    l xiaosa "!!!"
    l xiaosa "这里是?!!!图书馆?"
    l xiaosa "好羞耻的姿势!!!"
    l xiaosa "怎么全身腰酸背痛的？"
    l xiaosa "一定是王大爷趁我睡着偷偷打了我一顿"
    l xiaosa "偷偷把我运到了这里,可恶的王大爷"
    l xiaosa "我手上这是？！！"
    l xiaosa "斗落大陆？"
    l xiaosa "什么!竟然要越级挑战八十一级魂斗罗？"
    l xiaosa "小子你可知道天才很多,中途夭折的可不少"
    hide luokun with dissolve
    show zaochuan with dissolve
    z smile "罗坤桑!原来你在这里呀!"
    z xuanyun "腿翘这么高,不愧是罗坤桑呢,跟雨姐一样带派"
    l "带派不老铁"
    l "不过...你是？？"
    z smile "哎？罗坤桑你怎么了？"
    z smile "我是早川雪乃呀,园艺社的那个"
    l "早川...雪乃？"
    l "没听过啊"
    z sad "呜...罗坤桑你别吓我"
    z sad "昨天我们还在樱花道说要做干花书签呢"
    l "樱花道？干花书签？"
    l "你怕不是认错人了吧"
    z sad "罗坤桑...你是不是被车撞傻了..."
    l "喂喂,你别哭啊"
    l "我就是一觉醒来啥都不记得了"
    z sad "你昨天在樱花道被车撞了"
    z sad "粉色小熊内裤都被撞出来了"
    z smile "不过很可爱呢"
    z smile "然后你自顾自地说着一些奇怪的话语人就突然不见了"
    z xuanyun "好像是什么...用钩锁...按B回城...之类的"
    z xuanyun "今天来图书馆就看到你在这里了"
    l "粉色...小熊内裤？！"
    l "你在胡说什么啊喂！"
    z smile "不过现在罗坤桑平安回来就好啦"
    l xiaosa "所以...我们很熟吗？"
    z smile "当然啦！我每天都在樱花道等你经过哦"
    l xiaosa "等我？为什么？"
    z shy "因、因为...不告诉你"
    n "早川捂着脸跑开了"
    n "留罗坤一人在风中凌乱"
    stop music
    return
label classroom:
    play music "bgm/搞怪的小曲.opus"
    scene classroom with rule_3 
    wang "罗坤醒醒,怎么又睡着了"
    wang "老师刚刚叫你呢"
    wang "你差点就被扣平时分了"
    wang "还好我说你有点不舒服"
    show luokun ceyan1 
    l ceyan1 "我又睡着了？"
    l ceyan1 "刚才又是梦吗"
    l ceyan1 "怎么不是36D黑长直啊"
    wang "你小子睡睡糊涂了?还36D..."
    wang "（低头音压低,耳尖发红）再说...黑长直有什么好的"
    voice "voice/平时分.ogg"
    l ceyan2 "好,扣完算了,不要了,tmd平时分而已,起码会给我打点的"
    l ceyan2 "不过,还是谢啦"
    n "王大爷看着罗坤的侧颜"
    n "心脏突然漏跳了一拍"
    wang "（耳尖发红）你..你说什么呢"
    l ceyan2 "刚刚我..."
    n "罗坤略带戏谑的顿了顿"
    l ceyan2 "梦到了你"
    wang "(娇呼一声)啊？"
    wang "你..."
    n "王大爷转过头,假装翻书"
    n "耳根却红得快要滴血"
    wang "（小声嘀咕）你不会对我有想法吧"
    l ceyan2 "（猛地回头）你说什么？"
    l ceyan2 "其实是梦到你趁我睡着偷偷打了我一顿"
    wang "我怎么会打你..你坏.."
    show luokun smile at Transform(xalign=0.5, yalign=0.5) with dissolve
    n "罗坤看着王大爷被调戏得窘迫的样子"
    n "嘴角不经意的扬了扬"
    stop music
    return
    