label two:
    play music  "bgm/日常的小曲2.opus"
    scene eat at Transform(yalign=0.0) with rule_1 
    show wudao at Transform(xalign=0.0, yalign=0.5) with dissolve
    w wugu "哼，杂鱼就是事多，不知道让女生等很没礼貌吗"
    n "罗坤挠了挠头"
    l "我这是又..睡着了?"
    n "罗坤嘴角一笑,眼睛一眯,便看向对面"
    l "(嘴角一撇)怎么还不是36D啊"
    w shy "你.."
    w shy "你在看哪里！"
    n "罗坤挑了挑眉"
    l "当然是看你啊"
    l "不然还能看空气？"
    w "（脸颊微红）臭杂鱼!"
    w cute "谁允许你这么看我的..."
    n "雾岛的声音引来邻桌侧目，她慌忙低下头，双手攥紧裙摆"
    l "开玩笑的啦"
    l "不过说真的，你今天怎么没穿校服？"
    n "罗坤的目光落在雾岛的米白色连衣裙上，裙摆绣着细碎的冰晶纹路"
    w shy "好看吗"
    w shy "（小声）听说这家店适合穿裙子来..."
    l "挺好看的,很适合你"
    w "!!!"
    show wudao at Transform(xalign=0.0, yalign=0.5) 
    w xuanyun "（猛地别过脸，耳根红透）谁、谁要你夸啊！"
    w xuanyun "杂鱼的审美能好到哪里去"
    l "好好好，我审美差"
    l "那你特意点的限定布丁，我可就自己吃了"
    w jingya "（立刻转头）不行！那是我想吃的！"
    n "罗坤笑着挖了一勺布丁递到雾岛嘴边"
    l "喏，给你"
    w jingya "（愣住，脸颊更红）你、你干什么！"
    l "喂你吃啊，不然你又要闹脾气"
    w cute "（犹豫两秒，飞快张嘴咬住勺子）呜..."
    n "布丁的甜味在舌尖化开，雾岛的耳朵都红成了樱桃色"
    w xuanyun "笨蛋...不会自己吃吗"
    w wugu "喂...你嘴角"
    l "嗯？有什么吗"
    w cute "（突然起身凑近）别动"
    n "雾岛掏出纸巾，指尖擦过罗坤的嘴角"
    l "!"
    w cute "（猛地退坐回原位，脸红到耳根）脏死了，看着就烦"
    l "谢..谢谢"
    w shy "（低头戳米饭）...笨蛋"
    n "罗坤大快朵颐时,没注意到雾岛攥紧裙摆的手"
    n "指节都泛白了"
    w shy "（小声）放学后...去天台,我有事情问你"
    l jiya "哦?雾岛同学是..."
    l jiya "行啊,不过得请我喝可乐"
    w shy "（耳根更红）...知道了"
    return
label restaurant:
    play music  "bgm/日常的小曲.opus"
    scene restaurant with rule_1
    show luokun  faceme
    wang "罗坤你发什么呆呢"
    l faceme "啊？没、没什么"
    wang "又在幻想你的36D吗"
    l faceme "(顿了顿)那可没有啊"
    l facesmile "话说...早上在教室"
    l facesmile "你脸怎么那么红？"
    wang "（猛地呛到）咳、咳咳！"
    wang "谁、谁脸红了！那是被太阳晒的！"
    l facesmile "（挑眉）教室哪来的太阳"
    wang "（戳着碗里的米饭）反正就是...热的"
    n "罗坤看着王大爷耳根泛粉的样子，突然笑出声"
    return

